// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TRASH.InfrastructureServices.Gateways.Database;

namespace TRASH.WebService.Migrations
{
    [DbContext(typeof(TRASHContext))]
    [Migration("20200604001051_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("TRASH.DomainObjects.trash", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("YardArea")
                        .HasColumnType("TEXT");

                    b.Property<string>("YardName")
                        .HasColumnType("TEXT");

                    b.Property<string>("YardType")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TRASHs");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            YardArea = "18",
                            YardName = "Контейнерная площадка № 1987645",
                            YardType = "контейнерная площадка"
                        },
                        new
                        {
                            Id = 2L,
                            YardArea = "16.25",
                            YardName = "Контейнерная площадка № 1987649",
                            YardType = "контейнерная площадка"
                        },
                        new
                        {
                            Id = 3L,
                            YardArea = "10.4",
                            YardName = "Контейнерная площадка № 1987653",
                            YardType = "контейнерная площадка"
                        },
                        new
                        {
                            Id = 4L,
                            YardArea = "16.25",
                            YardName = "Контейнерная площадка № 1987654",
                            YardType = "контейнерная площадка"
                        },
                        new
                        {
                            Id = 5L,
                            YardArea = "280",
                            YardName = "Контейнерная площадка № 1987655",
                            YardType = "контейнерная площадка"
                        },
                        new
                        {
                            Id = 6L,
                            YardArea = "13",
                            YardName = "Контейнерная площадка № 1987656",
                            YardType = "контейнерная площадка"
                        },
                        new
                        {
                            Id = 7L,
                            YardArea = "13",
                            YardName = "Контейнерная площадка № 1987659",
                            YardType = "контейнерная площадка"
                        },
                        new
                        {
                            Id = 8L,
                            YardArea = "10",
                            YardName = "Контейнерная площадка № 1987660",
                            YardType = "контейнерная площадка"
                        },
                        new
                        {
                            Id = 9L,
                            YardArea = "21",
                            YardName = "Контейнерная площадка № 1987661",
                            YardType = "контейнерная площадка"
                        },
                        new
                        {
                            Id = 10L,
                            YardArea = "11",
                            YardName = "Контейнерная площадка № 1987662",
                            YardType = "контейнерная площадка"
                        },
                        new
                        {
                            Id = 11L,
                            YardArea = "16",
                            YardName = "Контейнерная площадка № 1987663",
                            YardType = "контейнерная площадка"
                        },
                        new
                        {
                            Id = 12L,
                            YardArea = "33",
                            YardName = "Контейнерная площадка № 1987665",
                            YardType = "контейнерная площадка"
                        },
                        new
                        {
                            Id = 13L,
                            YardArea = "4",
                            YardName = "Контейнерная площадка № 1987666",
                            YardType = "контейнерная площадка"
                        },
                        new
                        {
                            Id = 14L,
                            YardArea = "15",
                            YardName = "Контейнерная площадка № 1987668",
                            YardType = "контейнерная площадка"
                        },
                        new
                        {
                            Id = 15L,
                            YardArea = "22",
                            YardName = "Контейнерная площадка № 1987669",
                            YardType = "контейнерная площадка"
                        },
                        new
                        {
                            Id = 16L,
                            YardArea = "16",
                            YardName = "Контейнерная площадка № 1987670",
                            YardType = "контейнерная площадка"
                        },
                        new
                        {
                            Id = 17L,
                            YardArea = "10",
                            YardName = "Контейнерная площадка № 1987671",
                            YardType = "контейнерная площадка"
                        },
                        new
                        {
                            Id = 18L,
                            YardArea = "14",
                            YardName = "Контейнерная площадка № 1987672",
                            YardType = "контейнерная площадка"
                        },
                        new
                        {
                            Id = 19L,
                            YardArea = "21",
                            YardName = "Контейнерная площадка № 1987674",
                            YardType = "контейнерная площадка"
                        },
                        new
                        {
                            Id = 20L,
                            YardArea = "6",
                            YardName = "Контейнерная площадка № 1987675",
                            YardType = "контейнерная площадка"
                        },
                        new
                        {
                            Id = 21L,
                            YardArea = "10",
                            YardName = "Контейнерная площадка № 1987676",
                            YardType = "контейнерная площадка"
                        },
                        new
                        {
                            Id = 22L,
                            YardArea = "18",
                            YardName = "Контейнерная площадка № 1987677",
                            YardType = "контейнерная площадка"
                        },
                        new
                        {
                            Id = 23L,
                            YardArea = "9",
                            YardName = "Контейнерная площадка № 1987679",
                            YardType = "контейнерная площадка"
                        },
                        new
                        {
                            Id = 24L,
                            YardArea = "7",
                            YardName = "Контейнерная площадка № 1987680",
                            YardType = "контейнерная площадка"
                        },
                        new
                        {
                            Id = 25L,
                            YardArea = "6",
                            YardName = "Контейнерная площадка № 1987681",
                            YardType = "контейнерная площадка"
                        },
                        new
                        {
                            Id = 26L,
                            YardArea = "16",
                            YardName = "Контейнерная площадка № 1987682",
                            YardType = "контейнерная площадка"
                        },
                        new
                        {
                            Id = 27L,
                            YardArea = "23",
                            YardName = "Контейнерная площадка № 1987684",
                            YardType = "контейнерная площадка"
                        },
                        new
                        {
                            Id = 28L,
                            YardArea = "8",
                            YardName = "Контейнерная площадка № 1987685",
                            YardType = "контейнерная площадка"
                        },
                        new
                        {
                            Id = 29L,
                            YardArea = "9",
                            YardName = "Контейнерная площадка № 1987686",
                            YardType = "контейнерная площадка"
                        },
                        new
                        {
                            Id = 30L,
                            YardArea = "6",
                            YardName = "Контейнерная площадка № 1987687",
                            YardType = "контейнерная площадка"
                        },
                        new
                        {
                            Id = 31L,
                            YardArea = "13",
                            YardName = "Контейнерная площадка № 1987688",
                            YardType = "контейнерная площадка"
                        },
                        new
                        {
                            Id = 32L,
                            YardArea = "6",
                            YardName = "Контейнерная площадка № 1987689",
                            YardType = "контейнерная площадка"
                        },
                        new
                        {
                            Id = 33L,
                            YardArea = "6",
                            YardName = "Контейнерная площадка № 1987690",
                            YardType = "контейнерная площадка"
                        },
                        new
                        {
                            Id = 34L,
                            YardArea = "14",
                            YardName = "Контейнерная площадка № 1987691",
                            YardType = "контейнерная площадка"
                        },
                        new
                        {
                            Id = 35L,
                            YardArea = "7",
                            YardName = "Контейнерная площадка № 1987692",
                            YardType = "контейнерная площадка"
                        },
                        new
                        {
                            Id = 36L,
                            YardArea = "10",
                            YardName = "Контейнерная площадка № 1987693",
                            YardType = "контейнерная площадка"
                        },
                        new
                        {
                            Id = 37L,
                            YardArea = "32",
                            YardName = "Контейнерная площадка № 1987696",
                            YardType = "контейнерная площадка"
                        },
                        new
                        {
                            Id = 38L,
                            YardArea = "14",
                            YardName = "Контейнерная площадка № 1987697",
                            YardType = "контейнерная площадка"
                        },
                        new
                        {
                            Id = 39L,
                            YardArea = "8",
                            YardName = "Контейнерная площадка № 1987698",
                            YardType = "контейнерная площадка"
                        },
                        new
                        {
                            Id = 40L,
                            YardArea = "16",
                            YardName = "Контейнерная площадка № 1987699",
                            YardType = "контейнерная площадка"
                        },
                        new
                        {
                            Id = 41L,
                            YardArea = "14",
                            YardName = "Контейнерная площадка № 1987700",
                            YardType = "контейнерная площадка"
                        },
                        new
                        {
                            Id = 42L,
                            YardArea = "9",
                            YardName = "Контейнерная площадка № 1987702",
                            YardType = "контейнерная площадка"
                        },
                        new
                        {
                            Id = 43L,
                            YardArea = "7",
                            YardName = "Контейнерная площадка № 1987703",
                            YardType = "контейнерная площадка"
                        },
                        new
                        {
                            Id = 44L,
                            YardArea = "12",
                            YardName = "Контейнерная площадка № 1987704",
                            YardType = "контейнерная площадка"
                        },
                        new
                        {
                            Id = 45L,
                            YardArea = "14",
                            YardName = "Контейнерная площадка № 1987705",
                            YardType = "контейнерная площадка"
                        },
                        new
                        {
                            Id = 46L,
                            YardArea = "10",
                            YardName = "Контейнерная площадка № 1987707",
                            YardType = "контейнерная площадка"
                        },
                        new
                        {
                            Id = 47L,
                            YardArea = "9",
                            YardName = "Контейнерная площадка № 1987708",
                            YardType = "контейнерная площадка"
                        },
                        new
                        {
                            Id = 48L,
                            YardArea = "4",
                            YardName = "Контейнерная площадка № 1987709",
                            YardType = "контейнерная площадка"
                        },
                        new
                        {
                            Id = 49L,
                            YardArea = "7",
                            YardName = "Контейнерная площадка № 1987712",
                            YardType = "контейнерная площадка"
                        },
                        new
                        {
                            Id = 50L,
                            YardArea = "13.55",
                            YardName = "Контейнерная площадка № 1987715",
                            YardType = "контейнерная площадка"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
